package contract

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const operationManifestPath = "contract/operations.yaml"

type GeneratedArtifact struct {
	Path     string
	Contents []byte
}

func CompileOperationArtifacts(repositoryRoot string) ([]GeneratedArtifact, error) {
	sourcePath := filepath.Join(repositoryRoot, operationManifestPath)
	source, err := os.ReadFile(sourcePath)
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", operationManifestPath, err)
	}
	manifest, err := DecodeOperationManifest(source)
	if err != nil {
		return nil, err
	}
	normalized, err := MarshalNormalizedOperationManifest(manifest)
	if err != nil {
		return nil, fmt.Errorf("encode normalized operation manifest: %w", err)
	}
	canonical, err := decodeNormalizedOperationManifest(normalized)
	if err != nil {
		return nil, err
	}
	if err := ValidateOperationAnnotations(repositoryRoot, canonical); err != nil {
		return nil, err
	}
	routes, err := renderOperationRoutes(canonical)
	if err != nil {
		return nil, err
	}
	operationIDs := make(map[string]bool, len(canonical.Operations))
	for _, operation := range canonical.Operations {
		operationIDs[operation.ID] = true
	}
	consumerManifest, err := compileConsumerManifest(repositoryRoot, operationIDs)
	if err != nil {
		return nil, err
	}
	consumerNormalized, err := MarshalNormalizedConsumerManifest(consumerManifest)
	if err != nil {
		return nil, fmt.Errorf("encode normalized consumer manifest: %w", err)
	}
	artifacts := []GeneratedArtifact{
		{Path: consumerNormalizedPath, Contents: consumerNormalized},
		{Path: "contract/operations.normalized.json", Contents: normalized},
		{Path: "docs/en/consumer-compatibility.md", Contents: renderConsumerCompatibility(consumerManifest, "en")},
		{Path: "docs/en/api-rpc-compatibility.md", Contents: renderOperationTable(canonical, "en")},
		{Path: "docs/ko/consumer-compatibility.md", Contents: renderConsumerCompatibility(consumerManifest, "ko")},
		{Path: "docs/ko/api-rpc-compatibility.md", Contents: renderOperationTable(canonical, "ko")},
		{Path: "internal/contractspec/operations_gen.go", Contents: routes},
	}
	sort.Slice(artifacts, func(i, j int) bool { return artifacts[i].Path < artifacts[j].Path })
	return artifacts, nil
}

func WriteOperationArtifacts(repositoryRoot string) error {
	artifacts, err := CompileOperationArtifacts(repositoryRoot)
	if err != nil {
		return err
	}
	for _, artifact := range artifacts {
		path := filepath.Join(repositoryRoot, artifact.Path)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return fmt.Errorf("create directory for %s: %w", artifact.Path, err)
		}
		if err := os.WriteFile(path, artifact.Contents, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", artifact.Path, err)
		}
	}
	return nil
}

func CheckOperationArtifacts(repositoryRoot string) error {
	artifacts, err := CompileOperationArtifacts(repositoryRoot)
	if err != nil {
		return err
	}
	var dirty []string
	for _, artifact := range artifacts {
		actual, err := os.ReadFile(filepath.Join(repositoryRoot, artifact.Path))
		if err != nil || !bytes.Equal(actual, artifact.Contents) {
			dirty = append(dirty, artifact.Path)
		}
	}
	if len(dirty) != 0 {
		return fmt.Errorf("generated operation artifacts are stale: %s; run `make contract-generate`", strings.Join(dirty, ", "))
	}
	return nil
}

func decodeNormalizedOperationManifest(contents []byte) (OperationManifest, error) {
	decoder := json.NewDecoder(bytes.NewReader(contents))
	decoder.DisallowUnknownFields()
	var manifest OperationManifest
	if err := decoder.Decode(&manifest); err != nil {
		return OperationManifest{}, fmt.Errorf("decode normalized operation manifest: %w", err)
	}
	if err := ensureJSONEOF(decoder); err != nil {
		return OperationManifest{}, err
	}
	if err := ValidateOperationManifest(manifest); err != nil {
		return OperationManifest{}, err
	}
	return normalizeOperationManifest(manifest), nil
}

func ensureJSONEOF(decoder *json.Decoder) error {
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		if err == nil {
			return errors.New("decode normalized operation manifest: trailing JSON value")
		}
		return fmt.Errorf("decode normalized operation manifest: %w", err)
	}
	return nil
}

func renderOperationRoutes(manifest OperationManifest) ([]byte, error) {
	var output strings.Builder
	output.WriteString("// Code generated by contractctl; DO NOT EDIT.\n\npackage contractspec\n\n")
	output.WriteString("import \"sort\"\n\n")
	output.WriteString("type RESTRouteSpec struct {\n\tOperationID string\n\tComponent string\n\tMethod string\n\tPath string\n\tDiscovery bool\n}\n\n")
	output.WriteString("func (s RESTRouteSpec) Pattern() string { return s.Method + \" \" + s.Path }\n\n")
	output.WriteString("type GRPCRPCSpec struct {\n\tOperationID string\n\tComponent string\n\tService string\n\tMethod string\n\tSupport string\n}\n\n")
	output.WriteString("var generatedRESTRouteSpecs = []RESTRouteSpec{\n")
	for _, operation := range manifest.Operations {
		if operation.REST == nil || operation.Support == SupportUnsupported {
			continue
		}
		fmt.Fprintf(&output, "\t{OperationID: %q, Component: %q, Method: %q, Path: %q, Discovery: %t},\n",
			operation.ID, operation.Component, operation.REST.Method, operation.REST.Path, operation.REST.Discovery)
	}
	output.WriteString("}\n\nvar generatedGRPCRPCSpecs = []GRPCRPCSpec{\n")
	for _, operation := range manifest.Operations {
		if operation.GRPC == nil || operation.Support == SupportUnsupported {
			continue
		}
		fmt.Fprintf(&output, "\t{OperationID: %q, Component: %q, Service: %q, Method: %q, Support: %q},\n",
			operation.ID, operation.Component, operation.GRPC.Service, operation.GRPC.Method, operation.Support)
	}
	output.WriteString("}\n\n")
	output.WriteString(`func RESTRoute(operationID string) (RESTRouteSpec, bool) {
	index := sort.Search(len(generatedRESTRouteSpecs), func(index int) bool {
		return generatedRESTRouteSpecs[index].OperationID >= operationID
	})
	if index == len(generatedRESTRouteSpecs) || generatedRESTRouteSpecs[index].OperationID != operationID {
		return RESTRouteSpec{}, false
	}
	return generatedRESTRouteSpecs[index], true
}

func RESTRoutes(components ...string) []RESTRouteSpec {
	allowed := stringSet(components...)
	var routes []RESTRouteSpec
	for _, route := range generatedRESTRouteSpecs {
		if len(allowed) != 0 && !allowed[route.Component] {
			continue
		}
		routes = append(routes, route)
	}
	return append([]RESTRouteSpec(nil), routes...)
}

func GRPCRPCs(components ...string) []GRPCRPCSpec {
	allowed := stringSet(components...)
	var methods []GRPCRPCSpec
	for _, method := range generatedGRPCRPCSpecs {
		if len(allowed) != 0 && !allowed[method.Component] {
			continue
		}
		methods = append(methods, method)
	}
	return append([]GRPCRPCSpec(nil), methods...)
}

func stringSet(values ...string) map[string]bool {
	result := make(map[string]bool, len(values))
	for _, value := range values {
		result[value] = true
	}
	return result
}
`)
	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated operation routes: %w", err)
	}
	return formatted, nil
}

func renderOperationTable(manifest OperationManifest, language string) []byte {
	var output strings.Builder
	sourceURLs := make(map[string]string, len(manifest.Sources))
	for _, source := range manifest.Sources {
		sourceURLs[source.ID] = source.URL
	}
	if language == "ko" {
		output.WriteString("<!-- doc-id: api-rpc-compatibility -->\n<!-- lang: ko -->\n\n")
		output.WriteString("[English](../en/api-rpc-compatibility.md) | [한국어](api-rpc-compatibility.md)\n\n")
		output.WriteString("# API 및 RPC 호환성\n\n")
		output.WriteString("이 문서는 `contract/operations.normalized.json`에서 생성됩니다. 지원 상태와 검증 수준은 코드 값으로 표기합니다.\n\n")
		output.WriteString("<!-- section: operations -->\n")
		output.WriteString("| 프로토콜 | Operation ID | API 또는 RPC | 메서드 | 경로 | 지원 | 검증 | 조건 | 지원 입력 | 제한 정책 | 의도적 제외 범위 | 제한 사항 | 공식 출처 | 테스트 | 이슈 |\n")
	} else {
		output.WriteString("<!-- doc-id: api-rpc-compatibility -->\n<!-- lang: en -->\n\n")
		output.WriteString("[English](api-rpc-compatibility.md) | [한국어](../ko/api-rpc-compatibility.md)\n\n")
		output.WriteString("# API and RPC compatibility\n\n")
		output.WriteString("This document is generated from `contract/operations.normalized.json`. Support and verification use their canonical enum values.\n\n")
		output.WriteString("<!-- section: operations -->\n")
		output.WriteString("| Protocol | Operation ID | API or RPC | Method | Path | Support | Verification | Conditions | Supported input | Limitation policy | By-design scopes | Limitations | Official sources | Tests | Issues |\n")
	}
	output.WriteString("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n")
	for _, operation := range manifest.Operations {
		api, method, path := operation.ID, "-", "-"
		if operation.REST != nil {
			method, path = operation.REST.Method, operation.REST.Path
		} else {
			api = operation.GRPC.Service + "/" + operation.GRPC.Method
			method = operation.GRPC.Method
		}
		supported, limitations := operation.SupportedInput.EN, operation.Limitations.EN
		if language == "ko" {
			supported, limitations = operation.SupportedInput.KO, operation.Limitations.KO
		}
		fmt.Fprintf(&output, "| `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | `%s` | %s | %s | `%s` | %s | %s | %s | %s | %s |\n",
			operation.Protocol, operation.ID, markdownCell(api), method, markdownCell(path), operation.Support, operation.Verification,
			markdownConditions(operation.Conditions, language), markdownCell(supported), operation.Limitations.Policy,
			markdownByDesignScopes(operation.Limitations.ByDesign), markdownCell(limitations), markdownSources(operation.Sources, sourceURLs),
			markdownReferences(operation.Tests), markdownIssues(operation.Issues))
	}
	return []byte(output.String())
}

func markdownByDesignScopes(scopes []ByDesignScope) string {
	if len(scopes) == 0 {
		return "-"
	}
	values := make([]string, len(scopes))
	for index, scope := range scopes {
		values[index] = "`" + string(scope) + "`"
	}
	return strings.Join(values, "<br>")
}

func markdownConditions(conditions []OperationCondition, language string) string {
	if len(conditions) == 0 {
		return "-"
	}
	values := make([]string, len(conditions))
	for index, condition := range conditions {
		description := condition.EN
		if language == "ko" {
			description = condition.KO
		}
		values[index] = fmt.Sprintf("`%s=%t` (`%s`, `%s`; %s): %s", condition.Setting, condition.Equals,
			condition.Effect, condition.Verification, markdownReferences(condition.Tests), markdownCell(description))
	}
	return strings.Join(values, "<br>")
}

func markdownSources(values []string, URLs map[string]string) string {
	links := make([]string, len(values))
	for index, value := range values {
		links[index] = "[" + value + "](" + URLs[value] + ")"
	}
	return strings.Join(links, "<br>")
}

func markdownIssues(values []string) string {
	if len(values) == 0 {
		return "-"
	}
	links := make([]string, len(values))
	for index, value := range values {
		links[index] = "[" + value + "](https://github.com/leeyh0216/go-bemu/issues/" + strings.TrimPrefix(value, "#") + ")"
	}
	return strings.Join(links, "<br>")
}

func markdownCell(value string) string {
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "\n", "<br>")
	return value
}

func markdownReferences(values []string) string {
	if len(values) == 0 {
		return "-"
	}
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = "`" + value + "`"
	}
	return strings.Join(quoted, "<br>")
}
