// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: load_jobs.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createLoadJob = `-- name: CreateLoadJob :execrows
INSERT INTO bqemu_load_jobs (
    project_id, location_key, location, job_id, configuration_version,
    configuration_json, configuration_digest, state, error_reason, error_message,
    created_at, started_at, ended_at, input_files, input_bytes, output_rows, output_bytes
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?12, ?13,
    ?14, ?15, ?16, ?17
)
ON CONFLICT (project_id, location_key, job_id) DO NOTHING
`

type CreateLoadJobParams struct {
	ProjectID            string
	LocationKey          string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	InputFiles           int64
	InputBytes           int64
	OutputRows           int64
	OutputBytes          int64
}

func (q *Queries) CreateLoadJob(ctx context.Context, arg CreateLoadJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createLoadJob,
		arg.ProjectID,
		arg.LocationKey,
		arg.Location,
		arg.JobID,
		arg.ConfigurationVersion,
		arg.ConfigurationJson,
		arg.ConfigurationDigest,
		arg.State,
		arg.ErrorReason,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.InputFiles,
		arg.InputBytes,
		arg.OutputRows,
		arg.OutputBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLoadJob = `-- name: GetLoadJob :one
SELECT project_id, location, job_id, configuration_version,
    configuration_json, configuration_digest, state, error_reason, error_message,
    created_at, started_at, ended_at, input_files, input_bytes, output_rows, output_bytes
FROM bqemu_load_jobs
WHERE project_id = ?1
  AND location_key = ?2
  AND job_id = ?3
`

type GetLoadJobParams struct {
	ProjectID   string
	LocationKey string
	JobID       string
}

type GetLoadJobRow struct {
	ProjectID            string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	InputFiles           int64
	InputBytes           int64
	OutputRows           int64
	OutputBytes          int64
}

func (q *Queries) GetLoadJob(ctx context.Context, arg GetLoadJobParams) (GetLoadJobRow, error) {
	row := q.db.QueryRowContext(ctx, getLoadJob, arg.ProjectID, arg.LocationKey, arg.JobID)
	var i GetLoadJobRow
	err := row.Scan(
		&i.ProjectID,
		&i.Location,
		&i.JobID,
		&i.ConfigurationVersion,
		&i.ConfigurationJson,
		&i.ConfigurationDigest,
		&i.State,
		&i.ErrorReason,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.InputFiles,
		&i.InputBytes,
		&i.OutputRows,
		&i.OutputBytes,
	)
	return i, err
}

const listInterruptedLoadJobs = `-- name: ListInterruptedLoadJobs :many
SELECT project_id, location, job_id, configuration_version,
    configuration_json, configuration_digest, state, error_reason, error_message,
    created_at, started_at, ended_at, input_files, input_bytes, output_rows, output_bytes
FROM bqemu_load_jobs
WHERE state IN ('PENDING', 'RUNNING')
ORDER BY created_at, project_id, location_key, job_id
`

type ListInterruptedLoadJobsRow struct {
	ProjectID            string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	InputFiles           int64
	InputBytes           int64
	OutputRows           int64
	OutputBytes          int64
}

func (q *Queries) ListInterruptedLoadJobs(ctx context.Context) ([]ListInterruptedLoadJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInterruptedLoadJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInterruptedLoadJobsRow{}
	for rows.Next() {
		var i ListInterruptedLoadJobsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Location,
			&i.JobID,
			&i.ConfigurationVersion,
			&i.ConfigurationJson,
			&i.ConfigurationDigest,
			&i.State,
			&i.ErrorReason,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.InputFiles,
			&i.InputBytes,
			&i.OutputRows,
			&i.OutputBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoadJobs = `-- name: ListLoadJobs :many
SELECT project_id, location, job_id, configuration_version,
    configuration_json, configuration_digest, state, error_reason, error_message,
    created_at, started_at, ended_at, input_files, input_bytes, output_rows, output_bytes
FROM bqemu_load_jobs
WHERE project_id = ?1
ORDER BY created_at, job_id, location_key
`

type ListLoadJobsRow struct {
	ProjectID            string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	InputFiles           int64
	InputBytes           int64
	OutputRows           int64
	OutputBytes          int64
}

func (q *Queries) ListLoadJobs(ctx context.Context, projectID string) ([]ListLoadJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoadJobs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoadJobsRow{}
	for rows.Next() {
		var i ListLoadJobsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Location,
			&i.JobID,
			&i.ConfigurationVersion,
			&i.ConfigurationJson,
			&i.ConfigurationDigest,
			&i.State,
			&i.ErrorReason,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.InputFiles,
			&i.InputBytes,
			&i.OutputRows,
			&i.OutputBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoadJobsAtLocation = `-- name: ListLoadJobsAtLocation :many
SELECT project_id, location, job_id, configuration_version,
    configuration_json, configuration_digest, state, error_reason, error_message,
    created_at, started_at, ended_at, input_files, input_bytes, output_rows, output_bytes
FROM bqemu_load_jobs
WHERE project_id = ?1
  AND location_key = ?2
ORDER BY created_at, job_id
`

type ListLoadJobsAtLocationParams struct {
	ProjectID   string
	LocationKey string
}

type ListLoadJobsAtLocationRow struct {
	ProjectID            string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	InputFiles           int64
	InputBytes           int64
	OutputRows           int64
	OutputBytes          int64
}

func (q *Queries) ListLoadJobsAtLocation(ctx context.Context, arg ListLoadJobsAtLocationParams) ([]ListLoadJobsAtLocationRow, error) {
	rows, err := q.db.QueryContext(ctx, listLoadJobsAtLocation, arg.ProjectID, arg.LocationKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLoadJobsAtLocationRow{}
	for rows.Next() {
		var i ListLoadJobsAtLocationRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Location,
			&i.JobID,
			&i.ConfigurationVersion,
			&i.ConfigurationJson,
			&i.ConfigurationDigest,
			&i.State,
			&i.ErrorReason,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.InputFiles,
			&i.InputBytes,
			&i.OutputRows,
			&i.OutputBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoadJob = `-- name: UpdateLoadJob :execrows
UPDATE bqemu_load_jobs SET
    location = ?1, configuration_version = ?2,
    configuration_json = ?3,
    configuration_digest = ?4, state = ?5,
    error_reason = ?6, error_message = ?7,
    created_at = ?8, started_at = ?9,
    ended_at = ?10, input_files = ?11,
    input_bytes = ?12, output_rows = ?13,
    output_bytes = ?14
WHERE project_id = ?15
  AND location_key = ?16
  AND job_id = ?17
`

type UpdateLoadJobParams struct {
	Location             string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	InputFiles           int64
	InputBytes           int64
	OutputRows           int64
	OutputBytes          int64
	ProjectID            string
	LocationKey          string
	JobID                string
}

func (q *Queries) UpdateLoadJob(ctx context.Context, arg UpdateLoadJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateLoadJob,
		arg.Location,
		arg.ConfigurationVersion,
		arg.ConfigurationJson,
		arg.ConfigurationDigest,
		arg.State,
		arg.ErrorReason,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.InputFiles,
		arg.InputBytes,
		arg.OutputRows,
		arg.OutputBytes,
		arg.ProjectID,
		arg.LocationKey,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
