// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: load_mutations.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createLoadMutation = `-- name: CreateLoadMutation :exec
INSERT INTO bqemu_load_mutations (
    mutation_id, project_id, location_key, location, job_id, configuration_digest,
    plan_fingerprint, destination_json, before_schema_json, publication, phase,
    input_files, input_bytes, output_rows, created_destination, updated_destination, revision
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10, 'PREPARED',
    ?11, ?12, NULL, NULL, NULL, 1
)
`

type CreateLoadMutationParams struct {
	MutationID          string
	ProjectID           string
	LocationKey         string
	Location            string
	JobID               string
	ConfigurationDigest string
	PlanFingerprint     string
	DestinationJson     string
	BeforeSchemaJson    string
	Publication         string
	InputFiles          int64
	InputBytes          int64
}

func (q *Queries) CreateLoadMutation(ctx context.Context, arg CreateLoadMutationParams) error {
	_, err := q.db.ExecContext(ctx, createLoadMutation,
		arg.MutationID,
		arg.ProjectID,
		arg.LocationKey,
		arg.Location,
		arg.JobID,
		arg.ConfigurationDigest,
		arg.PlanFingerprint,
		arg.DestinationJson,
		arg.BeforeSchemaJson,
		arg.Publication,
		arg.InputFiles,
		arg.InputBytes,
	)
	return err
}

const getLoadMutation = `-- name: GetLoadMutation :one
SELECT mutation_id, project_id, location, job_id,
    configuration_digest, plan_fingerprint, destination_json, before_schema_json,
    publication, phase, input_files, input_bytes, output_rows,
    created_destination, updated_destination
FROM bqemu_load_mutations
WHERE mutation_id = ?1
`

type GetLoadMutationRow struct {
	MutationID          string
	ProjectID           string
	Location            string
	JobID               string
	ConfigurationDigest string
	PlanFingerprint     string
	DestinationJson     string
	BeforeSchemaJson    string
	Publication         string
	Phase               string
	InputFiles          int64
	InputBytes          int64
	OutputRows          sql.NullInt64
	CreatedDestination  sql.NullInt64
	UpdatedDestination  sql.NullInt64
}

func (q *Queries) GetLoadMutation(ctx context.Context, mutationID string) (GetLoadMutationRow, error) {
	row := q.db.QueryRowContext(ctx, getLoadMutation, mutationID)
	var i GetLoadMutationRow
	err := row.Scan(
		&i.MutationID,
		&i.ProjectID,
		&i.Location,
		&i.JobID,
		&i.ConfigurationDigest,
		&i.PlanFingerprint,
		&i.DestinationJson,
		&i.BeforeSchemaJson,
		&i.Publication,
		&i.Phase,
		&i.InputFiles,
		&i.InputBytes,
		&i.OutputRows,
		&i.CreatedDestination,
		&i.UpdatedDestination,
	)
	return i, err
}

const listRecoverableLoadMutations = `-- name: ListRecoverableLoadMutations :many
SELECT mutation_id, project_id, location, job_id,
    configuration_digest, plan_fingerprint, destination_json, before_schema_json,
    publication, phase, input_files, input_bytes, output_rows,
    created_destination, updated_destination
FROM bqemu_load_mutations
WHERE phase IN ('PREPARED', 'PHYSICAL') OR (phase = 'APPLIED' AND EXISTS (
    SELECT 1 FROM bqemu_load_jobs AS job
    WHERE job.project_id = bqemu_load_mutations.project_id
      AND job.location_key = bqemu_load_mutations.location_key
      AND job.job_id = bqemu_load_mutations.job_id
      AND job.state <> 'DONE'
))
ORDER BY mutation_id
`

type ListRecoverableLoadMutationsRow struct {
	MutationID          string
	ProjectID           string
	Location            string
	JobID               string
	ConfigurationDigest string
	PlanFingerprint     string
	DestinationJson     string
	BeforeSchemaJson    string
	Publication         string
	Phase               string
	InputFiles          int64
	InputBytes          int64
	OutputRows          sql.NullInt64
	CreatedDestination  sql.NullInt64
	UpdatedDestination  sql.NullInt64
}

func (q *Queries) ListRecoverableLoadMutations(ctx context.Context) ([]ListRecoverableLoadMutationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecoverableLoadMutations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecoverableLoadMutationsRow{}
	for rows.Next() {
		var i ListRecoverableLoadMutationsRow
		if err := rows.Scan(
			&i.MutationID,
			&i.ProjectID,
			&i.Location,
			&i.JobID,
			&i.ConfigurationDigest,
			&i.PlanFingerprint,
			&i.DestinationJson,
			&i.BeforeSchemaJson,
			&i.Publication,
			&i.Phase,
			&i.InputFiles,
			&i.InputBytes,
			&i.OutputRows,
			&i.CreatedDestination,
			&i.UpdatedDestination,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLoadMutationAborted = `-- name: MarkLoadMutationAborted :execrows
UPDATE bqemu_load_mutations
SET phase = 'ABORTED', output_rows = NULL, created_destination = NULL,
    updated_destination = NULL, revision = revision + 1
WHERE mutation_id = ?1 AND phase IN ('PREPARED', 'PHYSICAL')
`

func (q *Queries) MarkLoadMutationAborted(ctx context.Context, mutationID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markLoadMutationAborted, mutationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markLoadMutationApplied = `-- name: MarkLoadMutationApplied :execrows
UPDATE bqemu_load_mutations
SET phase = 'APPLIED', revision = revision + 1
WHERE mutation_id = ?1 AND phase = 'PHYSICAL'
`

func (q *Queries) MarkLoadMutationApplied(ctx context.Context, mutationID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markLoadMutationApplied, mutationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markLoadMutationPhysical = `-- name: MarkLoadMutationPhysical :execrows
UPDATE bqemu_load_mutations
SET phase = 'PHYSICAL', output_rows = ?1,
    created_destination = ?2,
    updated_destination = ?3, revision = revision + 1
WHERE mutation_id = ?4
  AND plan_fingerprint = ?5
  AND phase = 'PREPARED'
`

type MarkLoadMutationPhysicalParams struct {
	OutputRows         sql.NullInt64
	CreatedDestination sql.NullInt64
	UpdatedDestination sql.NullInt64
	MutationID         string
	PlanFingerprint    string
}

func (q *Queries) MarkLoadMutationPhysical(ctx context.Context, arg MarkLoadMutationPhysicalParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markLoadMutationPhysical,
		arg.OutputRows,
		arg.CreatedDestination,
		arg.UpdatedDestination,
		arg.MutationID,
		arg.PlanFingerprint,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
