// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
)

type BqemuDataset struct {
	ProjectID                    string
	DatasetID                    string
	FriendlyName                 string
	Description                  string
	Location                     string
	LabelsPresent                int64
	DefaultTableExpirationMs     sql.NullInt64
	DefaultPartitionExpirationMs sql.NullInt64
	CreatedAt                    string
	UpdatedAt                    string
	Hidden                       int64
}

type BqemuDatasetLabel struct {
	ProjectID  string
	DatasetID  string
	LabelKey   string
	LabelValue string
}

type BqemuLoadJob struct {
	ProjectID            string
	LocationKey          string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	InputFiles           int64
	InputBytes           int64
	OutputRows           int64
	OutputBytes          int64
}

type BqemuLoadMutation struct {
	MutationID          string
	ProjectID           string
	LocationKey         string
	Location            string
	JobID               string
	ConfigurationDigest string
	PlanFingerprint     string
	DestinationJson     string
	BeforeSchemaJson    string
	Publication         string
	Phase               string
	InputFiles          int64
	InputBytes          int64
	OutputRows          sql.NullInt64
	CreatedDestination  sql.NullInt64
	UpdatedDestination  sql.NullInt64
	Revision            int64
}

type BqemuProject struct {
	ProjectID    string
	FriendlyName string
	Description  string
	CreatedAt    string
	UpdatedAt    string
}

type BqemuQueryJob struct {
	ProjectID            string
	LocationKey          string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	ResultPresent        int64
	ResultSchemaJson     sql.NullString
	ResultRowCount       int64
	AffectedRows         int64
}

type BqemuReadSession struct {
	SessionName           string
	TableReference        string
	DataFormat            string
	SelectedFieldsJson    string
	RowRestrictionDigest  string
	RowRestrictionBytes   int64
	StreamCount           int64
	CreatedAtNs           int64
	ExpiresAtNs           int64
	SnapshotTimeNs        sql.NullInt64
	RetainedRowCount      int64
	RetainedBytes         int64
	EstimatedBytesScanned int64
	SchemaFingerprint     string
	LifecycleState        string
	LifecycleUpdatedAtNs  int64
}

type BqemuReadStream struct {
	StreamName  string
	SessionName string
	StreamIndex int64
	StartOffset int64
	EndOffset   int64
}

type BqemuRuntimePairGeneration struct {
	Singleton  int64
	Generation string
	CreatedAt  string
}

type BqemuTable struct {
	ProjectID                    string
	DatasetID                    string
	TableID                      string
	FriendlyName                 string
	Description                  string
	LabelsPresent                int64
	TableType                    string
	Location                     string
	ExpirationTime               sql.NullString
	TimePartitioningPresent      int64
	TimePartitioningType         sql.NullString
	TimePartitioningField        sql.NullString
	TimePartitioningExpirationMs sql.NullInt64
	RangePartitioningPresent     int64
	RangePartitioningField       sql.NullString
	RangeStart                   sql.NullInt64
	RangeEnd                     sql.NullInt64
	RangeInterval                sql.NullInt64
	ClusteringPresent            int64
	CreatedAt                    string
	UpdatedAt                    string
}

type BqemuTableClusteringField struct {
	ProjectID string
	DatasetID string
	TableID   string
	Ordinal   int64
	FieldName string
}

type BqemuTableField struct {
	ProjectID    string
	DatasetID    string
	TableID      string
	FieldPath    string
	ParentPath   sql.NullString
	Ordinal      int64
	FieldName    string
	FieldType    string
	FieldMode    string
	Description  string
	Precision    sql.NullInt64
	Scale        sql.NullInt64
	RoundingMode string
}

type BqemuTableLabel struct {
	ProjectID  string
	DatasetID  string
	TableID    string
	LabelKey   string
	LabelValue string
}

type BqemuTablePrimaryKeyColumn struct {
	ProjectID string
	DatasetID string
	TableID   string
	Ordinal   int64
	FieldName string
}

type BqemuView struct {
	ProjectID           string
	DatasetID           string
	ViewID              string
	FriendlyName        string
	Description         string
	LabelsJson          string
	QuerySql            string
	UseLegacySql        int64
	SchemaJson          string
	DependenciesJson    string
	AnalysisFingerprint string
	Location            string
	CreatedAt           string
	UpdatedAt           string
}

type BqemuWriteAppendReceipt struct {
	StreamName        string
	StartOffset       int64
	RowCount          int64
	SchemaFingerprint string
	PayloadDigest     string
	ReceiptPhase      string
	CreatedAtNs       int64
	UpdatedAtNs       int64
}

type BqemuWriteCommitGroup struct {
	GroupID          string
	ParentReference  string
	MemberCount      int64
	ExpectedRowCount int64
	CommitPhase      string
	CreatedAtNs      int64
	UpdatedAtNs      int64
	CommitTimeNs     sql.NullInt64
}

type BqemuWriteCommitMember struct {
	GroupID          string
	MemberIndex      int64
	StreamName       string
	ExpectedRowCount int64
}

type BqemuWriteStream struct {
	StreamName              string
	ProjectID               string
	DatasetID               string
	TableID                 string
	StreamType              string
	StreamState             string
	CreateTimeNs            int64
	CommitTimeNs            sql.NullInt64
	Location                string
	SchemaJson              string
	RowCount                int64
	NextOffset              int64
	WriterSchemaFingerprint string
	LastActivityNs          int64
	OperationKind           string
	OperationPhase          string
	OperationToken          string
	CleanupPhase            string
	CleanupAttempts         int64
	Revision                int64
}
