// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query_jobs.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createQueryJob = `-- name: CreateQueryJob :execrows
INSERT INTO bqemu_query_jobs (
    project_id, location_key, location, job_id, configuration_version,
    configuration_json, configuration_digest, state, error_reason, error_message,
    created_at, started_at, ended_at, result_present, result_schema_json,
    result_row_count, affected_rows
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10,
    ?11, ?12, ?13,
    ?14, ?15,
    ?16, ?17
)
ON CONFLICT (project_id, location_key, job_id) DO NOTHING
`

type CreateQueryJobParams struct {
	ProjectID            string
	LocationKey          string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	ResultPresent        int64
	ResultSchemaJson     sql.NullString
	ResultRowCount       int64
	AffectedRows         int64
}

func (q *Queries) CreateQueryJob(ctx context.Context, arg CreateQueryJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createQueryJob,
		arg.ProjectID,
		arg.LocationKey,
		arg.Location,
		arg.JobID,
		arg.ConfigurationVersion,
		arg.ConfigurationJson,
		arg.ConfigurationDigest,
		arg.State,
		arg.ErrorReason,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.ResultPresent,
		arg.ResultSchemaJson,
		arg.ResultRowCount,
		arg.AffectedRows,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getQueryJob = `-- name: GetQueryJob :one
SELECT project_id, location, job_id, configuration_version,
    configuration_json, configuration_digest, state, error_reason, error_message,
    created_at, started_at, ended_at, result_present, result_schema_json,
    result_row_count, affected_rows
FROM bqemu_query_jobs
WHERE project_id = ?1
  AND location_key = ?2
  AND job_id = ?3
`

type GetQueryJobParams struct {
	ProjectID   string
	LocationKey string
	JobID       string
}

type GetQueryJobRow struct {
	ProjectID            string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	ResultPresent        int64
	ResultSchemaJson     sql.NullString
	ResultRowCount       int64
	AffectedRows         int64
}

func (q *Queries) GetQueryJob(ctx context.Context, arg GetQueryJobParams) (GetQueryJobRow, error) {
	row := q.db.QueryRowContext(ctx, getQueryJob, arg.ProjectID, arg.LocationKey, arg.JobID)
	var i GetQueryJobRow
	err := row.Scan(
		&i.ProjectID,
		&i.Location,
		&i.JobID,
		&i.ConfigurationVersion,
		&i.ConfigurationJson,
		&i.ConfigurationDigest,
		&i.State,
		&i.ErrorReason,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.ResultPresent,
		&i.ResultSchemaJson,
		&i.ResultRowCount,
		&i.AffectedRows,
	)
	return i, err
}

const listQueryJobs = `-- name: ListQueryJobs :many
SELECT project_id, location, job_id, configuration_version,
    configuration_json, configuration_digest, state, error_reason, error_message,
    created_at, started_at, ended_at, result_present, result_schema_json,
    result_row_count, affected_rows
FROM bqemu_query_jobs
WHERE project_id = ?1
`

type ListQueryJobsRow struct {
	ProjectID            string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	ResultPresent        int64
	ResultSchemaJson     sql.NullString
	ResultRowCount       int64
	AffectedRows         int64
}

func (q *Queries) ListQueryJobs(ctx context.Context, projectID string) ([]ListQueryJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listQueryJobs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueryJobsRow{}
	for rows.Next() {
		var i ListQueryJobsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Location,
			&i.JobID,
			&i.ConfigurationVersion,
			&i.ConfigurationJson,
			&i.ConfigurationDigest,
			&i.State,
			&i.ErrorReason,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.ResultPresent,
			&i.ResultSchemaJson,
			&i.ResultRowCount,
			&i.AffectedRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueryJobsAtLocation = `-- name: ListQueryJobsAtLocation :many
SELECT project_id, location, job_id, configuration_version,
    configuration_json, configuration_digest, state, error_reason, error_message,
    created_at, started_at, ended_at, result_present, result_schema_json,
    result_row_count, affected_rows
FROM bqemu_query_jobs
WHERE project_id = ?1
  AND location_key = ?2
`

type ListQueryJobsAtLocationParams struct {
	ProjectID   string
	LocationKey string
}

type ListQueryJobsAtLocationRow struct {
	ProjectID            string
	Location             string
	JobID                string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	ResultPresent        int64
	ResultSchemaJson     sql.NullString
	ResultRowCount       int64
	AffectedRows         int64
}

func (q *Queries) ListQueryJobsAtLocation(ctx context.Context, arg ListQueryJobsAtLocationParams) ([]ListQueryJobsAtLocationRow, error) {
	rows, err := q.db.QueryContext(ctx, listQueryJobsAtLocation, arg.ProjectID, arg.LocationKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQueryJobsAtLocationRow{}
	for rows.Next() {
		var i ListQueryJobsAtLocationRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.Location,
			&i.JobID,
			&i.ConfigurationVersion,
			&i.ConfigurationJson,
			&i.ConfigurationDigest,
			&i.State,
			&i.ErrorReason,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.ResultPresent,
			&i.ResultSchemaJson,
			&i.ResultRowCount,
			&i.AffectedRows,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileInterruptedQueryJobs = `-- name: ReconcileInterruptedQueryJobs :execrows
UPDATE bqemu_query_jobs
SET state = 'DONE', error_reason = 'stopped', error_message = ?1,
    ended_at = ?2
WHERE state IN ('PENDING', 'RUNNING')
`

type ReconcileInterruptedQueryJobsParams struct {
	ErrorMessage sql.NullString
	EndedAt      sql.NullString
}

func (q *Queries) ReconcileInterruptedQueryJobs(ctx context.Context, arg ReconcileInterruptedQueryJobsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reconcileInterruptedQueryJobs, arg.ErrorMessage, arg.EndedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateQueryJob = `-- name: UpdateQueryJob :execrows
UPDATE bqemu_query_jobs SET
    location = ?1, configuration_version = ?2,
    configuration_json = ?3,
    configuration_digest = ?4, state = ?5,
    error_reason = ?6, error_message = ?7,
    created_at = ?8, started_at = ?9,
    ended_at = ?10, result_present = ?11,
    result_schema_json = ?12, result_row_count = ?13,
    affected_rows = ?14
WHERE project_id = ?15
  AND location_key = ?16
  AND job_id = ?17
`

type UpdateQueryJobParams struct {
	Location             string
	ConfigurationVersion int64
	ConfigurationJson    string
	ConfigurationDigest  string
	State                string
	ErrorReason          sql.NullString
	ErrorMessage         sql.NullString
	CreatedAt            string
	StartedAt            sql.NullString
	EndedAt              sql.NullString
	ResultPresent        int64
	ResultSchemaJson     sql.NullString
	ResultRowCount       int64
	AffectedRows         int64
	ProjectID            string
	LocationKey          string
	JobID                string
}

func (q *Queries) UpdateQueryJob(ctx context.Context, arg UpdateQueryJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateQueryJob,
		arg.Location,
		arg.ConfigurationVersion,
		arg.ConfigurationJson,
		arg.ConfigurationDigest,
		arg.State,
		arg.ErrorReason,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.StartedAt,
		arg.EndedAt,
		arg.ResultPresent,
		arg.ResultSchemaJson,
		arg.ResultRowCount,
		arg.AffectedRows,
		arg.ProjectID,
		arg.LocationKey,
		arg.JobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
