// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateLoadMutation(ctx context.Context, arg CreateLoadMutationParams) error
	GetLoadMutation(ctx context.Context, mutationID string) (GetLoadMutationRow, error)
	ListRecoverableLoadMutations(ctx context.Context) ([]ListRecoverableLoadMutationsRow, error)
	MarkLoadMutationAborted(ctx context.Context, mutationID string) (int64, error)
	MarkLoadMutationApplied(ctx context.Context, mutationID string) (int64, error)
	MarkLoadMutationPhysical(ctx context.Context, arg MarkLoadMutationPhysicalParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
