// Code generated by contractctl; DO NOT EDIT.

package contractspec

import "sort"

type RESTRouteSpec struct {
	OperationID string
	Component   string
	Method      string
	Path        string
	Discovery   bool
}

func (s RESTRouteSpec) Pattern() string { return s.Method + " " + s.Path }

type GRPCRPCSpec struct {
	OperationID string
	Component   string
	Service     string
	Method      string
	Support     string
}

var generatedRESTRouteSpecs = []RESTRouteSpec{
	{OperationID: "bigquery.datasets.delete", Component: "public-core", Method: "DELETE", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}", Discovery: true},
	{OperationID: "bigquery.datasets.get", Component: "public-core", Method: "GET", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}", Discovery: true},
	{OperationID: "bigquery.datasets.insert", Component: "public-core", Method: "POST", Path: "/bigquery/v2/projects/{projectId}/datasets", Discovery: true},
	{OperationID: "bigquery.datasets.list", Component: "public-core", Method: "GET", Path: "/bigquery/v2/projects/{projectId}/datasets", Discovery: true},
	{OperationID: "bigquery.datasets.patch", Component: "public-core", Method: "PATCH", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}", Discovery: true},
	{OperationID: "bigquery.datasets.update", Component: "public-core", Method: "PUT", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}", Discovery: true},
	{OperationID: "bigquery.jobs.get", Component: "public-query", Method: "GET", Path: "/bigquery/v2/projects/{projectId}/jobs/{jobId}", Discovery: true},
	{OperationID: "bigquery.jobs.getQueryResults", Component: "public-query", Method: "GET", Path: "/bigquery/v2/projects/{projectId}/queries/{jobId}", Discovery: true},
	{OperationID: "bigquery.jobs.insert", Component: "public-query", Method: "POST", Path: "/bigquery/v2/projects/{projectId}/jobs", Discovery: true},
	{OperationID: "bigquery.jobs.insert.resumable", Component: "public-query", Method: "POST", Path: "/resumable/upload/bigquery/v2/projects/{projectId}/jobs", Discovery: false},
	{OperationID: "bigquery.jobs.insert.resumable-resume", Component: "public-query", Method: "PUT", Path: "/resumable/upload/bigquery/v2/projects/{projectId}/jobs", Discovery: false},
	{OperationID: "bigquery.jobs.insert.upload", Component: "public-query", Method: "POST", Path: "/upload/bigquery/v2/projects/{projectId}/jobs", Discovery: false},
	{OperationID: "bigquery.jobs.insert.upload-resume", Component: "public-query", Method: "PUT", Path: "/upload/bigquery/v2/projects/{projectId}/jobs", Discovery: false},
	{OperationID: "bigquery.jobs.list", Component: "public-query", Method: "GET", Path: "/bigquery/v2/projects/{projectId}/jobs", Discovery: true},
	{OperationID: "bigquery.jobs.query", Component: "public-query", Method: "POST", Path: "/bigquery/v2/projects/{projectId}/queries", Discovery: true},
	{OperationID: "bigquery.projects.list", Component: "public-core", Method: "GET", Path: "/bigquery/v2/projects", Discovery: true},
	{OperationID: "bigquery.tabledata.list", Component: "public-tabledata", Method: "GET", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}/data", Discovery: true},
	{OperationID: "bigquery.tables.delete", Component: "public-core", Method: "DELETE", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}", Discovery: true},
	{OperationID: "bigquery.tables.get", Component: "public-core", Method: "GET", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}", Discovery: true},
	{OperationID: "bigquery.tables.insert", Component: "public-core", Method: "POST", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables", Discovery: true},
	{OperationID: "bigquery.tables.list", Component: "public-core", Method: "GET", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables", Discovery: true},
	{OperationID: "bigquery.tables.patch", Component: "public-core", Method: "PATCH", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}", Discovery: true},
	{OperationID: "bigquery.tables.update", Component: "public-core", Method: "PUT", Path: "/bigquery/v2/projects/{projectId}/datasets/{datasetId}/tables/{tableId}", Discovery: true},
	{OperationID: "bqemu.admin.goroutines.get", Component: "admin", Method: "GET", Path: "/bqemu/v1/admin/diagnostics/goroutines", Discovery: false},
	{OperationID: "bqemu.admin.health", Component: "admin", Method: "GET", Path: "/healthz", Discovery: false},
	{OperationID: "bqemu.admin.runtime.get", Component: "admin", Method: "GET", Path: "/bqemu/v1/admin/diagnostics/runtime", Discovery: false},
	{OperationID: "bqemu.capabilities.get", Component: "public-query", Method: "GET", Path: "/bqemu/v1/capabilities", Discovery: false},
	{OperationID: "bqemu.console.assets", Component: "public-console", Method: "GET", Path: "/console/", Discovery: false},
	{OperationID: "bqemu.console.get", Component: "public-query", Method: "GET", Path: "/bqemu/v1/console", Discovery: false},
	{OperationID: "bqemu.console.redirect", Component: "public-console", Method: "GET", Path: "/", Discovery: false},
	{OperationID: "bqemu.discovery.get", Component: "public-core", Method: "GET", Path: "/$discovery/rest", Discovery: false},
	{OperationID: "bqemu.discovery.googleapis.get", Component: "public-core", Method: "GET", Path: "/discovery/v1/apis/bigquery/v2/rest", Discovery: false},
	{OperationID: "bqemu.health.live", Component: "public-core", Method: "GET", Path: "/healthz", Discovery: false},
	{OperationID: "bqemu.health.ready", Component: "public-core", Method: "GET", Path: "/readyz", Discovery: false},
	{OperationID: "bqemu.projects.create", Component: "public-core", Method: "POST", Path: "/bqemu/v1/projects", Discovery: false},
	{OperationID: "bqemu.projects.delete", Component: "public-core", Method: "DELETE", Path: "/bqemu/v1/projects/{projectId}", Discovery: false},
	{OperationID: "bqemu.projects.get", Component: "public-core", Method: "GET", Path: "/bqemu/v1/projects/{projectId}", Discovery: false},
	{OperationID: "bqemu.projects.list", Component: "public-core", Method: "GET", Path: "/bqemu/v1/projects", Discovery: false},
}

var generatedGRPCRPCSpecs = []GRPCRPCSpec{
	{OperationID: "grpc.bigquery-read.create-read-session", Component: "storage-read", Service: "google.cloud.bigquery.storage.v1.BigQueryRead", Method: "CreateReadSession", Support: "partial"},
	{OperationID: "grpc.bigquery-read.read-rows", Component: "storage-read", Service: "google.cloud.bigquery.storage.v1.BigQueryRead", Method: "ReadRows", Support: "partial"},
	{OperationID: "grpc.bigquery-read.split-read-stream", Component: "storage-read", Service: "google.cloud.bigquery.storage.v1.BigQueryRead", Method: "SplitReadStream", Support: "registered"},
	{OperationID: "grpc.bigquery-write.append-rows", Component: "storage-write", Service: "google.cloud.bigquery.storage.v1.BigQueryWrite", Method: "AppendRows", Support: "partial"},
	{OperationID: "grpc.bigquery-write.batch-commit-write-streams", Component: "storage-write", Service: "google.cloud.bigquery.storage.v1.BigQueryWrite", Method: "BatchCommitWriteStreams", Support: "partial"},
	{OperationID: "grpc.bigquery-write.create-write-stream", Component: "storage-write", Service: "google.cloud.bigquery.storage.v1.BigQueryWrite", Method: "CreateWriteStream", Support: "partial"},
	{OperationID: "grpc.bigquery-write.finalize-write-stream", Component: "storage-write", Service: "google.cloud.bigquery.storage.v1.BigQueryWrite", Method: "FinalizeWriteStream", Support: "partial"},
	{OperationID: "grpc.bigquery-write.flush-rows", Component: "storage-write", Service: "google.cloud.bigquery.storage.v1.BigQueryWrite", Method: "FlushRows", Support: "registered"},
	{OperationID: "grpc.bigquery-write.get-write-stream", Component: "storage-write", Service: "google.cloud.bigquery.storage.v1.BigQueryWrite", Method: "GetWriteStream", Support: "partial"},
	{OperationID: "grpc.health.check", Component: "grpc-health", Service: "grpc.health.v1.Health", Method: "Check", Support: "implemented"},
	{OperationID: "grpc.health.list", Component: "grpc-health", Service: "grpc.health.v1.Health", Method: "List", Support: "implemented"},
	{OperationID: "grpc.health.watch", Component: "grpc-health", Service: "grpc.health.v1.Health", Method: "Watch", Support: "implemented"},
	{OperationID: "grpc.reflection-v1.server-reflection-info", Component: "grpc-reflection", Service: "grpc.reflection.v1.ServerReflection", Method: "ServerReflectionInfo", Support: "implemented"},
	{OperationID: "grpc.reflection-v1alpha.server-reflection-info", Component: "grpc-reflection", Service: "grpc.reflection.v1alpha.ServerReflection", Method: "ServerReflectionInfo", Support: "implemented"},
}

func RESTRoute(operationID string) (RESTRouteSpec, bool) {
	index := sort.Search(len(generatedRESTRouteSpecs), func(index int) bool {
		return generatedRESTRouteSpecs[index].OperationID >= operationID
	})
	if index == len(generatedRESTRouteSpecs) || generatedRESTRouteSpecs[index].OperationID != operationID {
		return RESTRouteSpec{}, false
	}
	return generatedRESTRouteSpecs[index], true
}

func RESTRoutes(components ...string) []RESTRouteSpec {
	allowed := stringSet(components...)
	var routes []RESTRouteSpec
	for _, route := range generatedRESTRouteSpecs {
		if len(allowed) != 0 && !allowed[route.Component] {
			continue
		}
		routes = append(routes, route)
	}
	return append([]RESTRouteSpec(nil), routes...)
}

func GRPCRPCs(components ...string) []GRPCRPCSpec {
	allowed := stringSet(components...)
	var methods []GRPCRPCSpec
	for _, method := range generatedGRPCRPCSpecs {
		if len(allowed) != 0 && !allowed[method.Component] {
			continue
		}
		methods = append(methods, method)
	}
	return append([]GRPCRPCSpec(nil), methods...)
}

func stringSet(values ...string) map[string]bool {
	result := make(map[string]bool, len(values))
	for _, value := range values {
		result[value] = true
	}
	return result
}
