package config

import (
	"fmt"
	"strings"
)

// ConfigReferenceMarkdown renders the checked-in EN/KO reference from the
// same descriptor source used by overrides and generated aliases.
func ConfigReferenceMarkdown(language string) (string, error) {
	var title, introduction, environment string
	switch language {
	case "en":
		title = "# Configuration reference"
		introduction = "Generated from `internal/config.Config`; do not edit manually. Scalar leaves accept YAML, `--set path=value`, and their generated environment aliases. Collections accept a strict YAML `--set` value but have no environment alias. BQEMU's public contract follows the [BigQuery REST API](https://cloud.google.com/bigquery/docs/reference/rest)."
		environment = "Environment"
	case "ko":
		title = "# 설정 참조"
		introduction = "`internal/config.Config`에서 생성합니다. 직접 수정하지 마십시오. scalar leaf는 YAML, `--set path=value`, 생성된 환경 변수 별칭을 받습니다. collection은 strict YAML `--set` 값을 받지만 환경 변수 별칭은 없습니다. BQEMU의 공개 계약은 [BigQuery REST API](https://cloud.google.com/bigquery/docs/reference/rest)를 따릅니다."
		environment = "환경 변수"
	default:
		return "", fmt.Errorf("unsupported reference language %q", language)
	}
	var builder strings.Builder
	builder.WriteString("<!-- doc-id: config-reference -->\n")
	builder.WriteString("<!-- lang: " + language + " -->\n")
	builder.WriteString("<!-- generated by cmd/configctl; DO NOT EDIT -->\n\n")
	if language == "en" {
		builder.WriteString("[English](config-reference.md) | [한국어](../ko/config-reference.md)\n\n")
	} else {
		builder.WriteString("[English](../en/config-reference.md) | [한국어](config-reference.md)\n\n")
	}
	builder.WriteString("<!-- section: reference -->\n")
	builder.WriteString(title + "\n\n" + introduction + "\n\n")
	builder.WriteString("| Path | Type | Default | " + environment + " |\n| --- | --- | --- | --- |\n")
	for _, leaf := range LeafDescriptors() {
		builder.WriteString(fmt.Sprintf("| `%s` | `%s` | `%s` | `%s` |\n", leaf.Path, leaf.Type, strings.ReplaceAll(leaf.Default, "|", "\\|"), leaf.Environment))
	}
	return builder.String(), nil
}
